# Site settings
title: Antisèches techniques
email: tangui@tangui.eu.org
description: "Développement, administratation technique, mes antisèches sur le logiciel libre, GNU/Linux, PHP, Apache, l'Open source, Debian, ..."
baseurl: ""
url: "https://sergio.24eme.fr/"
twitter_username: 24emeSCOP
github_username:  24eme
include: [".htaccess"]
exclude: ["Makefile", "bin", "LICENSE"]

# Build settings
markdown: kramdown
permalink: pretty
